[package]
name = "affinity-health-sdk"
version = "0.2.0"
edition = "2021"
description = "Rust client for the Affinity API"
license = "MIT"
repository = "https://github.com/affinity-health/affinity-rust"
homepage = "https://github.com/affinity-health/affinity-rust"

[lib]
doctest = false

[dependencies]
futures-util = "0.3"
percent-encoding = "2"
httpdate = "1"
uuid = { version = "1", features = ["v4"] }
bytes = "1.0"
futures = "0.3"
reqwest = { version = "0.12", features = ["json", "stream", "gzip", "rustls-tls"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
tokio-test = "0.4"
